name: Task - Build Docker Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_containers:
    strategy:
      matrix:
        package: [docker/sui-node]
        platform: [linux/amd64, linux/arm64, linux/386]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
        with:
          buildkitd-flags: --debug

      - name: Create Docker Args
        id: docker_args
        shell: bash
        run: |
          GIT_REVISION="$(git describe --always --abbrev=12 --dirty --exclude '*')"
          BUILD_DATE="$(date -u +'%Y-%m-%d')"
          echo "git_revision=${GIT_REVISION}" >> $GITHUB_OUTPUT
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Build Sui Node
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          file: ./${{ matrix.package }}/Dockerfile
          push: false
          load: false
          platforms: ${{ matrix.platform }}
          build-args: |
            GIT_REVISION=${{ steps.docker_args.outputs.git_revision }}
            BUILD_DATE=${{ steps.docker_args.outputs.build_date }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,scope=${{ matrix.platform }},mode=max
