---
name: Task - Build & Push Docker Image

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  build_containers:
    strategy:
      matrix:
        package:
          [docker/sui-node]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Sui Node
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.package }}/Dockerfile
          push: true
          target: production
          tags: |
            ${{ env.DOCKER_REGISTRY}}/${{ matrix.package }}:latest
