---
name: Task - Build Docker Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_containers:
    strategy:
      matrix:
        package: [docker/sui-node]
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0
      - name: Create Docker Args
        id: Docker_args
        shell: bash
        run: |
          # Set the necessary environment variables for the Docker build
          GIT_REVISION="$(git describe --always --abbrev=12 --dirty --exclude '*')"
          BUILD_DATE="$(date -u +'%Y-%m-%d')"

          echo "GIT_REVISION=$GIT_REVISION" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
      - name: Build and push Sui Node
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          file: ./${{ matrix.package }}/Dockerfile
          push: false
          build-args: |
            GIT_REVISION=${{ steps.Docker_args.outputs.GIT_REVISION }}
            BUILD_DATE=${{ steps.Docker_args.outputs.BUILD_DATE }}
