name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'scripts/**'
      - '.github/**'

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_containers:
    name: Build Docker Image
    uses: ./.github/workflows/docker-test.yaml
