name: Workflow - Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., devnet-0.0.1)'
        required: true
  release:
    types: [published]

jobs:
  docker_release_build:
    name: Build and tag docker release
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=${{ github.event.inputs.version }}
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Docker Args
        id: docker_args
        shell: bash
        run: |
          GIT_REVISION="$(git describe --always --abbrev=12 --dirty --exclude '*')"
          BUILD_DATE="$(date -u +'%Y-%m-%d')"
          echo "GIT_REVISION=${GIT_REVISION}" >> $GITHUB_OUTPUT
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Build and push Sui Node
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/sui-node/Dockerfile
          push: true
          platforms: linux/amd64,linux/386
          build-args: |
            GIT_REVISION=${{ steps.docker_args.outputs.GIT_REVISION }}
            BUILD_DATE=${{ steps.docker_args.outputs.BUILD_DATE }}
          tags: |
            ghcr.io/${{ github.repository }}/docker/sui-node:latest
            ghcr.io/${{ github.repository }}/docker/sui-node:${{ steps.version.outputs.VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.description=Public Pui Node Docker image
            org.opencontainers.image.version=${{ steps.version.outputs.VERSION }}
            org.opencontainers.image.licenses=Apache-2.0
